/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/hall/hall.gltf --transform --types 
Files: ./public/hall/hall.gltf [57.92KB] > C:\Users\zatag\3d-viewer\hall-transformed.glb [3.11MB] (-5276%)
*/

import * as THREE from 'three'
import React, { JSX } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    ground: THREE.Mesh
    Plane003: THREE.Mesh
    Plane005: THREE.Mesh
    wall002: THREE.Mesh
    Plane013: THREE.Mesh
    Cube001: THREE.Mesh
    Cylinder001: THREE.Mesh
    Plane015: THREE.Mesh
    Plane015_1: THREE.Mesh
    Plane015_2: THREE.Mesh
    Plane015_3: THREE.Mesh
    lamp: THREE.Mesh
  }
  materials: {
    PaletteMaterial001: THREE.MeshStandardMaterial
    Metal_hard: THREE.MeshStandardMaterial
    PaletteMaterial002: THREE.MeshPhysicalMaterial
    PaletteMaterial003: THREE.MeshStandardMaterial
    Metal_wall: THREE.MeshStandardMaterial
    PaletteMaterial004: THREE.MeshPhysicalMaterial
    Door_Material: THREE.MeshStandardMaterial
    PaletteMaterial005: THREE.MeshStandardMaterial
    PaletteMaterial006: THREE.MeshStandardMaterial
    PaletteMaterial007: THREE.MeshPhysicalMaterial
    lightbulb_led: THREE.MeshStandardMaterial
  }
  animations: any[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/hall/hall-transformed.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.ground.geometry} material={materials.PaletteMaterial001} />
      <mesh geometry={nodes.Plane003.geometry} material={materials.Metal_hard} />
      <mesh geometry={nodes.Plane005.geometry} material={materials.PaletteMaterial002} />
      <mesh geometry={nodes.wall002.geometry} material={materials.PaletteMaterial003} />
      <mesh geometry={nodes.Plane013.geometry} material={materials.Metal_wall} />
      <mesh geometry={nodes.Cube001.geometry} material={materials.PaletteMaterial004} />
      <mesh geometry={nodes.Cylinder001.geometry} material={nodes.Cylinder001.material} />
      <mesh geometry={nodes.lamp.geometry} material={materials.lightbulb_led} />
      <mesh geometry={nodes.Plane015.geometry} material={materials.Door_Material} />
      <mesh geometry={nodes.Plane015_1.geometry} material={materials.PaletteMaterial005} />
      <mesh geometry={nodes.Plane015_2.geometry} material={materials.PaletteMaterial006} />
      <mesh geometry={nodes.Plane015_3.geometry} material={materials.PaletteMaterial007} />
    </group>
  )
}

useGLTF.preload('/hall/hall-transformed.glb')
